name = "TensorQEC"
uuid = "0500ac79-7fb5-4262-aaea-37bb1845d1ef"
authors = ["Zhongyi Ni"]
version = "1.0.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
TensorInference = "c2297e78-99bd-40ad-871d-f50e56b81012"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"

[compat]
Combinatorics = "1"
DelimitedFiles = "1"
HiGHS = "1.13.0"
JuMP = "1.24.0"
LinearAlgebra = "1"
OMEinsum = "0.8.2"
PrettyTables = "2.3"
TensorInference = "0.4"
Yao = "0.9"
julia = "1"
